#!/bin/bash
#InYourHeart Was Here:)
echo "#================2EASY4HACK================#
#   _|_|     _|_|_|_|   _|  _|     _|    _|#
# _|    _|   _|         _|  _|     _|    _|#
#     _|     _|_|_|     _|_|_|_|   _|_|_|_|#
#   _|       _|             _|     _|    _|#
# _|_|_|_|   _|_|_|_|       _|     _|    _|#
#================InYourHeart===============#
~~~~~~~~~~######~~~~~~~~~~
| Author : InYourHeart   |
| Versi  : 1.0           |
~~~~~~~~~~######~~~~~~~~~~
Tool Termux!!
To Easy For Hacktivitas:v
-_-_-_-_-_-_-_-_-_-_-_-_-_
~~~~~~Silahkan Pilih~~~~~~
------MetasploitUser------
1.  Install Metasploit
2.  Install Tmux-Bunch
3.  Install Ngrok
4.  Install Shodan
------**************------
------PhishingTools-------
5.  Install Weeman
6.  Install Blackeye
7.  Install SocialFish
------*************-------
-------SosmedTools--------
8.  Install BlackHydra
9.  Install Cupp
10. Install MBF
11. Install Instahack
12. Install Twiter Sniper
13. Install b3v3r
-------***********--------
---------UsersBOT---------
14. Install Instabot
15. Install Bot Komen Fb
16. Install Bot Like Fb
17. Install Chuckyfix
---------********---------
---------Defacers---------
18. Install Sqlmap
19. Install LFISuite
20. Install Bingoo
21. Install LiteScript
22. Install XAttacker
23. Install Diejoubu
----------Others----------
24. Install Java
25. Install Fedora
26. Install Kali Nethunter
27. Install Debian
28. Install Ubuntu
29. Install Kali Linux
******Special Tools*******
30. Install Blackarch
----------######----------" | lolcat 
read -p "root@2E4H #:" gg

if [ $gg = 1 ] || [ $gg = 1 ]
then
clear
pkg update -y
pkg install wget -y
wget https://Auxilus.github.io/metasploit.sh
./metasploit.sh
cd $HOME/metasploit-framework
cd /data/data/com.termux/files/home && gem install bundle --pre
cd /data/data/com.termux/files/home && bundle config build.nokogiri --use-system-libraries
cd /data/data/com.termux/files/home && bundle install
echo "##################################" | lolcat
echo "Metasploit Telah Sukses Terinstall" | lolcat
echo "##################################" | lolcat
sleep 1
cd $HOME && ./msfconsole
fi

if [ $gg = 2 ] || [ $gg = 2 ]
then
clear
pkg update -y
pkg install axel -y
axel https://github.com/Hax4us/Tmux-Bunch/releases/download/2.4/Tmux-Bunch-2.4.tar.gz
tar -xf Tmux-Bunch-2.4.tar.gz
rm -f Tmux-Bunch-2.4.tar.gz
cd Tmux-Bunch && bash setup
echo "###################################"| lolcat
echo "Tmux-Bunch Telah Sukses Terinstall" | lolcat
echo "###################################"| lolcat
sleep 1
cd $HOME && tmuxbunch
fi

if [ $gg = 3 ] || [ $gg = 3 ]
then
clear
pkg update -y
pkg install wget -y
wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-arm.zip
unzip ngrok-stable-linux-arm.zip
rm -f ngrok-stable-linux-arm.zip
echo "#############################" | lolcat
echo "Ngrok Telah Sukses Terinstall" | lolcat
echo "#############################" | lolcat
sleep 1
fi

if [ $gg = 4 ] || [ $gg = 4 ]
then
clear
pkg update -y
pkg install python2 -y
pip2 install shodan
shodan init copas-api-shodan
shodan -h
fi

if [ $gg = 5 ] || [ $gg = 5 ]
then
clear
pkg update -y
pkg install python2 -y
pkg install git -y
git clone https://github.com/samyoyo/weeman
cd weeman
chmod +x weeman.py
echo "##############################" | lolcat
echo "Weeman Telah Sukses Terinstall" | lolcat
echo "##############################" | lolcat
sleep 1
python2 weeman.py
fi

if [ $gg = 6 ] || [ $gg = 6 ]
then
clear
pkg update -y
pkg install git
git clone https://github.com/thelinuxchoice/blackeye
cd blackeye
chmod +x blackeye.sh
echo "################################" | lolcat
echo "Blackeye Telah Sukses Terinstall" | lolcat
echo "################################" | lolcat
sleep 1
bash blackeye.sh
fi

if [ $gg = 7 ] || [ $gg = 7 ]
then
clear
pkg update -y
pkg install git -y
pkg install python -y
pkg install php -y
pkg install curl -y 
pkg install openssh -y
pkg install grep -y
pip3 install wget
git clone https://github.com/An0nUD4Y/SocialFish
cd SocialFish
chmod 777 SocialFish.py
echo "##################################" | lolcat
echo "SocialFish Telah Sukses Terinstall" | lolcat
echo "##################################" | lolcat
sleep 1
python SocialFish.py
fi

if [ $gg = 8 ] || [ $gg = 8 ]
then
clear
pkg update -y
pkg install git hydra -y
pkg install git -y
pkg install python -y
pkg install python2 -y
git clone https://github.com/Gameye98/Black-Hydra
cd Black-Hydra
chmod +x blackhydra.py
echo "##################################" | lolcat
echo "BlackHydra Telah Sukses Terinstall" | lolcat
echo "##################################" | lolcat
sleep 1
python2 blackhydra.py
fi

if [ $gg = 9 ] || [ $gg = 9 ]
then
clear
apt update && apt upgrade -y
apt install git python2 -y
git clone https://github.com/Mebus/cupp
cd cupp
echo "#############################" | lolcat
echo " Cupp Telah Sukses Terinstall" | lolcat
echo "#############################" | lolcat
sleep 1
python2 cupp.py
fi

if [ $gg = 10 ] || [ $gg = 10 ]
then
clear
pkg update -y
pkg install python2  -y
pkg install git -y
pip2 install mechanize
git clone https://github.com/pirmansx/mbf
cd mbf
echo "############################" | lolcat
echo " MBF Telah Sukses Terinstall" | lolcat
echo "############################" | lolcat
python2 MBF.py
fi
